### ISSUE TITLE
Garbled icons in control window on hrev58314

### ISSUE THREAD

**Issue by jckarter** [mt819/CannaIM#11]
On Haiku hrev58314, the IME appears to work normally; however, the control window shows garbled icons in the buttons:

![canna-garble](https://github.com/user-attachments/assets/a5ce9c29-f5d2-4672-b59f-31f8cf47dcc8)

**Comment by jckarter** [comment]
Not sure if this is Canna's or Haiku's issue; I also filed https://dev.haiku-os.org/ticket/19246 on the Haiku side.

**Comment by korli** [comment]
Should be fixed after [hrev58322](https://cgit.haiku-os.org/haiku/tag/?h=hrev58322)

**Comment by jckarter** [comment]
Yup, I updated my Haiku nightly and it looks right now. Thanks!
